spring:
  application:
    name: product-service
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: product_service
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/